/* ── Categorías ─────────────────────────────────────────────────────── */
var CATEGORIES = [
  {
    dbId: 1,
    id: "rapidas",
    label: "Comidas Rapidas",
    icon: "🍔",
    bg: "#fff8e1",
    accent: "#f59e0b",
    coverImg:
      "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&h=400&fit=crop&auto=format",
    description:
      "Burgers, tacos y wraps plant-based para cuando el tiempo apremia.",
  },
  {
    dbId: 2,
    id: "cenas",
    label: "Cenas",
    icon: "🍝",
    bg: "#ede9fe",
    accent: "#7c3aed",
    coverImg:
      "https://images.unsplash.com/photo-1473093226795-af9932fe5856?w=800&h=400&fit=crop&auto=format",
    description:
      "Platos elaborados para una cena especial o en familia.",
  },
  {
    dbId: 3,
    id: "bowls",
    label: "Bowls & Ensaladas",
    icon: "🥗",
    bg: "#dcfce7",
    accent: "#16a34a",
    coverImg:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format",
    description:
      "Bowls frescos, coloridos y cargados de nutrientes.",
  },
  {
    dbId: 4,
    id: "postres",
    label: "Postres",
    icon: "🍰",
    bg: "#fce7f3",
    accent: "#db2777",
    coverImg:
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&h=400&fit=crop&auto=format",
    description:
      "Dulces sin culpa: 100% veganos, sin lácteos ni huevos.",
  },
  {
    dbId: 5,
    id: "bebidas",
    label: "Bebidas",
    icon: "🥤",
    bg: "#dbeafe",
    accent: "#2563eb",
    coverImg:
      "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=800&h=400&fit=crop&auto=format",
    description:
      "Jugos naturales, smoothies y bebidas frías para hidratarte.",
  },
  {
    dbId: 6,
    id: "desayunos",
    label: "Desayunos",
    icon: "🌅",
    bg: "#fef9c3",
    accent: "#ca8a04",
    coverImg: "assets/image-6.png",
    description:
      "Empieza el día con energía: tostadas, granola y mucho más.",
  },
  {
    dbId: 7,
    id: "snacks",
    label: "Snacks",
    icon: "🍿",
    bg: "#f0fdf4",
    accent: "#15803d",
    coverImg:
      "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=800&h=400&fit=crop&auto=format",
    description:
      "Para el antojo del momento: chips, dips y snacks saludables.",
  },
];

/* ── Categorías de filtro promos ────────────────────────────────────── */
var PROMO_CATS = [
  "Todos",
  "Comidas Rapidas",
  "Cenas",
  "Bowls & Ensaladas",
  "Postres",
  "Bebidas",
  "Desayunos",
  "Snacks",
];

/* ── Promociones ────────────────────────────────────────────────────── */
var ALL_PROMOS = [
  {
    id: 1,
    dbId: 4,
    cat: "Bowls",
    badge: "HOY",
    badgeColor: "#388e3c",
    emoji: "🥗",
    title: "2x1 en Green Bowls",
    restaurant: "Green Bowl Colombia",
    desc: "Pide un bowl y llevate el segundo gratis.",
    img: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop&auto=format",
    originalPrice: "$28.000",
    price: "$14.000",
    discount: "50%",
    tag: "Mas pedido",
    endsIn: 6 * 3600,
  },
  {
    id: 2,
    dbId: 36,
    cat: "Bowls",
    badge: "-30%",
    badgeColor: "#0288d1",
    emoji: "🫐",
    title: "Acai Bowl premium",
    restaurant: "Acai House",
    desc: "30% de descuento en nuestro bowl de acai con granola.",
    img: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop&auto=format",
    originalPrice: "$22.000",
    price: "$15.400",
    discount: "30%",
    tag: "Vegano",
    endsIn: 3 * 3600 + 20 * 60,
  },
  {
    id: 3,
    dbId: 17,
    cat: "Bebidas",
    badge: "-30%",
    badgeColor: "#e91e63",
    emoji: "🥤",
    title: "30% en Smoothies",
    restaurant: "Smoothie Co.",
    desc: "Pide cualquier smoothie de la carta y llevate un segundo a mitad.",
    img: "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=600&h=400&fit=crop&auto=format",
    originalPrice: "$18.000",
    price: "$12.600",
    discount: "30%",
    tag: "Popular",
    endsIn: 11 * 3600,
  },
  {
    id: 4,
    dbId: 10,
    cat: "Bebidas",
    badge: "FREE",
    badgeColor: "#f57c00",
    emoji: "🍹",
    title: "Bebida gratis con tu pedido",
    restaurant: "Juice Bar",
    desc: "Agrega una bebida natural gratis en pedidos mayores a $35.000.",
    img: "https://images.unsplash.com/photo-1514995428455-447d4443fa7f?w=600&h=400&fit=crop&auto=format",
    originalPrice: "$12.000",
    price: "$0",
    discount: "100%",
    tag: "Sin codigo",
    endsIn: 2 * 3600 + 45 * 60,
  },
  {
    id: 5,
    dbId: 5,
    cat: "Tacos",
    badge: "FREE",
    badgeColor: "#00796b",
    emoji: "🌮",
    title: "Envio gratis en Tacos",
    restaurant: "Taco Natural",
    desc: "Sin costo de envio en pedidos mayores a $25.000.",
    img: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=600&h=400&fit=crop&auto=format",
    originalPrice: "$8.000",
    price: "$0",
    discount: "Envio",
    tag: "Plant-based",
    endsIn: 48 * 3600,
  },
  {
    id: 6,
    dbId: 9,
    cat: "Postres",
    badge: "3x2",
    badgeColor: "#c2185b",
    emoji: "🧡",
    title: "Pack dulce Shizen",
    restaurant: "Sweet Leaf",
    desc: "Lleva 3 postres veganos y paga solo 2.",
    img: "https://images.unsplash.com/photo-1629793980446-192d630f0dbe?w=600&h=400&fit=crop&auto=format",
    originalPrice: "$36.000",
    price: "$24.000",
    discount: "33%",
    tag: "Sin gluten",
    endsIn: 30 * 3600,
  },
  {
    id: 7,
    dbId: 8,
    cat: "Especiales",
    badge: "-50%",
    badgeColor: "#7b1fa2",
    emoji: "🌿",
    title: "Menu del dia vegano",
    restaurant: "Raw Garden",
    desc: "Menu completo: entrada, plato fuerte y postre vegano. 50% off.",
    img: "https://images.unsplash.com/photo-1644704170910-a0cdf183649b?w=600&h=400&fit=crop&auto=format",
    originalPrice: "$45.000",
    price: "$22.500",
    discount: "50%",
    tag: "Entre semana",
    endsIn: 5 * 3600 + 10 * 60,
  },
  {
    id: 8,
    dbId: 27,
    cat: "Especiales",
    badge: "NUEVO",
    badgeColor: "#388e3c",
    emoji: "🍜",
    title: "Ramen vegano especial",
    restaurant: "Ramen Vegano House",
    desc: "Nuevo en el menu: ramen de miso con tofu y fideos de arroz.",
    img: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop&auto=format",
    originalPrice: "$32.000",
    price: "$24.000",
    discount: "25%",
    tag: "Lanzamiento",
    endsIn: 72 * 3600,
  },
];
