/* ── Categorías ─────────────────────────────────────────────────────── */
var CATEGORIES = [
  {
    dbId: 1,
    id: "rapidas",
    label: "Comidas Rapidas",
    icon: "🍔",
    bg: "#fff8e1",
    accent: "#f59e0b",
    coverImg:
      "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&h=400&fit=crop&auto=format",
    description:
      "Burgers, tacos y wraps plant-based para cuando el tiempo apremia.",
  },
  {
    dbId: 2,
    id: "cenas",
    label: "Cenas",
    icon: "🍝",
    bg: "#ede9fe",
    accent: "#7c3aed",
    coverImg:
      "https://images.unsplash.com/photo-1473093226795-af9932fe5856?w=800&h=400&fit=crop&auto=format",
    description:
      "Platos elaborados para una cena especial o en familia.",
  },
  {
    dbId: 3,
    id: "bowls",
    label: "Bowls & Ensaladas",
    icon: "🥗",
    bg: "#dcfce7",
    accent: "#16a34a",
    coverImg:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format",
    description:
      "Bowls frescos, coloridos y cargados de nutrientes.",
  },
  {
    dbId: 4,
    id: "postres",
    label: "Postres",
    icon: "🍰",
    bg: "#fce7f3",
    accent: "#db2777",
    coverImg:
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&h=400&fit=crop&auto=format",
    description:
      "Dulces sin culpa: 100% veganos, sin lácteos ni huevos.",
  },
  {
    dbId: 5,
    id: "bebidas",
    label: "Bebidas",
    icon: "🥤",
    bg: "#dbeafe",
    accent: "#2563eb",
    coverImg:
      "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=800&h=400&fit=crop&auto=format",
    description:
      "Jugos naturales, smoothies y bebidas frías para hidratarte.",
  },
  {
    dbId: 6,
    id: "desayunos",
    label: "Desayunos",
    icon: "🌅",
    bg: "#fef9c3",
    accent: "#ca8a04",
    coverImg: "assets/image-6.png",
    description:
      "Empieza el día con energía: tostadas, granola y mucho más.",
  },
  {
    dbId: 7,
    id: "snacks",
    label: "Snacks",
    icon: "🍿",
    bg: "#f0fdf4",
    accent: "#15803d",
    coverImg:
      "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=800&h=400&fit=crop&auto=format",
    description:
      "Para el antojo del momento: chips, dips y snacks saludables.",
  },
];

/* ── Categorías de filtro promos ────────────────────────────────────── */
var PROMO_CATS = [
  "Todos",
  "Comidas Rapidas",
  "Cenas",
  "Bowls & Ensaladas",
  "Postres",
  "Bebidas",
  "Desayunos",
  "Snacks",
];

/* ── Promociones Fallback ────────────────────────────────────────────── */
var ALL_PROMOS = [
  {
    id: 1,
    dbId: 3,
    cat: "Comidas Rapidas",
    badge: "20% OFF",
    badgeColor: "#ea580c",
    emoji: "🍔",
    title: "Hamburguesa Vegana",
    restaurant: "Restaurante Vegano Central",
    desc: "Deliciosa hamburguesa vegetal con papas crujientes.",
    img: "../Imagenes_prueba/hamburguesavegana.jpg",
    originalPrice: "$25.000",
    price: "$20.000",
    discount: "20%",
    tag: "Más pedido",
    endsIn: 6 * 3600,
  },
  {
    id: 2,
    dbId: 19,
    cat: "Cenas",
    badge: "25% OFF",
    badgeColor: "#7c3aed",
    emoji: "🍝",
    title: "Pasta Vegana Alfredo",
    restaurant: "Restaurante Vegano Central",
    desc: "Pasta cremosa artesanal 100% libre de lácteos.",
    img: "../Imagenes_prueba/plato1.jpg",
    originalPrice: "$24.000",
    price: "$18.000",
    discount: "25%",
    tag: "Especial Cenas",
    endsIn: 8 * 3600,
  },
  {
    id: 3,
    dbId: 1,
    cat: "Bowls & Ensaladas",
    badge: "30% OFF",
    badgeColor: "#16a34a",
    emoji: "🥗",
    title: "Bowl Saludable Green",
    restaurant: "Restaurante Vegano Central",
    desc: "Bowl fresco cargado de vegetales de temporada y quinoa.",
    img: "../Imagenes_prueba/bowl.jpg",
    originalPrice: "$10.000",
    price: "$7.000",
    discount: "30%",
    tag: "Saludable",
    endsIn: 5 * 3600,
  },
  {
    id: 4,
    dbId: 20,
    cat: "Postres",
    badge: "25% OFF",
    badgeColor: "#db2777",
    emoji: "🍰",
    title: "Cheesecake Vegano",
    restaurant: "Restaurante Vegano Central",
    desc: "Cheesecake a base de castañas de cajú y frutos rojos.",
    img: "../Imagenes_prueba/postre1.jpg",
    originalPrice: "$10.000",
    price: "$7.500",
    discount: "25%",
    tag: "Postre del Día",
    endsIn: 12 * 3600,
  },
  {
    id: 5,
    dbId: 17,
    cat: "Bebidas",
    badge: "30% OFF",
    badgeColor: "#2563eb",
    emoji: "🥤",
    title: "Smoothie Verde Detox",
    restaurant: "Restaurante Vegano Central",
    desc: "Smoothie fresco de espinaca, piña y manzana verde.",
    img: "../Imagenes_prueba/bebida2.jpg",
    originalPrice: "$10.000",
    price: "$7.000",
    discount: "30%",
    tag: "Refrescante",
    endsIn: 4 * 3600,
  },
  {
    id: 6,
    dbId: 18,
    cat: "Desayunos",
    badge: "27% OFF",
    badgeColor: "#ca8a04",
    emoji: "🍳",
    title: "Tostada de Aguacate",
    restaurant: "Restaurante Vegano Central",
    desc: "Pan de masa madre con aguacate fresco y semillas.",
    img: "../Imagenes_prueba/desayuno1.jpg",
    originalPrice: "$11.000",
    price: "$8.000",
    discount: "27%",
    tag: "Desayuno",
    endsIn: 7 * 3600,
  },
  {
    id: 7,
    dbId: 30,
    cat: "Snacks",
    badge: "28% OFF",
    badgeColor: "#15803d",
    emoji: "🥨",
    title: "Gyozas de Verduras",
    restaurant: "Eco Market Chapinero",
    desc: "Gyozas al vapor rellenas de vegetales orientales.",
    img: "../Imagenes_prueba/snack1.jpg",
    originalPrice: "$14.000",
    price: "$10.000",
    discount: "28%",
    tag: "Snack Delicioso",
    endsIn: 10 * 3600,
  },
];
